name: flutter_paystack
description: A Flutter plugin for making payments via Paystack Payment Gateway. Completely supports Android and iOS.
version: 1.0.7
homepage: https://github.com/wilburt/flutter_paystack

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.20.1
  meta: ^1.8.0
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  matcher: ^0.12.16+1
  mockito: ^5.4.4

flutter:
  plugin:
    platforms:
      android:
        package: co.paystack.flutterpaystack
        pluginClass: FlutterPaystackPlugin
      ios:
        pluginClass: FlutterPaystackPlugin

  assets:
    - assets/images/

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.8.0"
